name: Feature Cicd Development

on:
  push:
    branches:
      - '*'

jobs: 
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: runtest
      run: echo "running on feature branch"

    - name: deploy
      run: echo "deploying on to the feature branch"